server:
  port: 5555
spring:
  application:
    name: api-gateway
zuul:
  routes:
    hello-server:
      path: /hello/**
      serviceId: hello-server
    feign-consumer:
      path: /feign-consumer/**
      serviceId: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
