server:
  port: 8020
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  httpclient:
    time-to-live: 10000
logging:
  level:
    com.open.cloud.feignconsumer.client.RefactorHelloService: debug
