spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
  redis:
    host: localhost
    port: 6379
  application:
    name: transaction-mq-task

server:
  port: 3105
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
